title: 1 BACH
description: > # this means to ignore newlines until "baseurl:"
  Curso de 1 BACH elaborado por May Calle, profesora
  en el I.E.S. San Vicente (San Vicente del Raspeig, Alicante)
baseurl: "/1bach" # the subpath of your site, e.g. /blog
url: "http://maycalle.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown